### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by ccarrero301** [dark-loop/webjobs-authorize#7]
> System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerOptions.set_TokenValidationParameters(Microsoft.IdentityModel.Tokens.TokenValidationParameters)'.
  Source=AuthenticationFunctionApp
  StackTrace:
   at AuthenticationFunctionApp.Startup.<>c.<Configure>b__0_1(JwtBearerOptions options) in C:\Users\Usuario\Desktop\AuthenticationFunctionApp\AuthenticationFunctionApp\Startup.cs:line 34
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Azure.WebJobs.Hosting.WebJobsOptionsFactory`1.Create(String name) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\OptionsFormatter\WebJobsOptionsFactory.cs:line 37
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

```
public void Configure(IWebJobsBuilder builder)
        {
            builder.AddAuthentication(options => { options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme; }).AddJwtBearer(
                options =>
                {
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuer = true,
                        ValidateAudience = true,
                        ValidateIssuerSigningKey = true,
                        ValidIssuer = "issuer",
                        ValidAudience = "aaudience",
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes("thekey"))
                    };
                });
        }
```

**Comment by artmasa** [comment]
Interesting. Not happening on my end.
What version of `Microsoft.AspNetCore.Authentication.JwtBearer` is your project referencing or loading?
Also what is the version of `Microsoft.IdentityModel.Tokens` that the project is loading?

I would like to test your exact setup on my end.

**Comment by ccarrero301** [comment]
Thanks for replying...

My setup is this one :

![image](https://user-images.githubusercontent.com/22915799/58777695-280be400-8595-11e9-82d6-70bcc2babd6a.png)

**Comment by artmasa** [comment]
I was able to replicate your error after matching your environment. 

It seems there is a clash between the `Microsoft.AspNetCore.Authentication.JwtBearer` (2.2.0) referenced by this repo. Which is the latest compatible version with .NET Standard 2.0. It seems the 3.00-preview versions are not compatible with .NET Standard 2.0
The `2.2.0` version of `Microsoft.AspNetCore.Authentication.JwtBearer` references the `5.3.0` versions of the `Microsoft.IdentityModel...` assemblies. You have installed the `5.4.0` version of these assemblies and there seems to be a strange clash in the arguments for the `TokenValidationParameters` property set method between these 2 versions.

Is there a new feature in `5.4.0` version of `Microsoft.IdentityModel...` assemblies that is required for your function apps? I verified that downgrading the version of these assemblies to 5.3.0 fixes the problem.

It's also interesting that the new `3.0.0-preview` versions of `Microsoft.AspNetCore.Authentication...` assemblies still reference the `5.3.0` version of `Microsoft.IdentityModel...` assemblies.

I'm afraid at this point nothing can be done to upgrade from 2.2.0 to 3.0.0-preview versions. Please let me know if you are able to find a solution other than downgrading.

**Comment by ccarrero301** [comment]
Thanks for the quick response. You are right the issue was with the following nugget packages

![image](https://user-images.githubusercontent.com/22915799/58821230-3d672980-85fa-11e9-91fd-1ccc5ac23269.png)

I am closing the issue.

Quick question, is it possible in the future to return a 401 when the authentication fails?

**Comment by artmasa** [comment]
@ccarrero301 What status code are you receiving? when I only configure JwtBearer I receive **401** with header **WWW-Authenticate: Bearer**
The framework does what it would do for ASP.NET. Make sure you specify the challenge scheme in your authentication setup:
```c#
builder
  .AddAuthentication(options =>
  {
    options.DeafultAutheticationScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
  })
  .AddJwtBearer(...
```

**Comment by ccarrero301** [comment]
@artmasa 
Awesome man thanks!
This is by far the best solution for the authentication problem in Azure functions.
Please publish a release version!

**Comment by artmasa** [comment]
@ccarrero301 I have updated the last comment on how to get 401 from JwtBearer
