### ISSUE TITLE
Any Plans for Azure Functions v3?

### ISSUE THREAD

**Issue by BenOravetz** [dark-loop/webjobs-authorize#8]
This is a great package for managing custom authorization with Azure Functions Web API and I was wondering if it will support Azure Functions v3.  Right now I have to enable compatibility mode when running this package on Azure Functions v3.

**Comment by artmasa** [comment]
I've been thinking about it. V3 has changed many things including namespaces. I was thinking about creating another repo for V3. I will look into that in the coming days.

**Comment by BenOravetz** [comment]
Sounds good.  I look forward to the improvements.

**Comment by artmasa** [comment]
Hey @BenOravetz, finally put the time to move it to V3.
This is the repo for targeting V3 Functions: https://github.com/dark-loop/functions-authorize

NUGET: `dotnet add package DarkLoop.Azure.Functions.Authorize --version 3.0.11-preview-210407-11`

**Comment by BenOravetz** [comment]
Thank you very much.  I'll start looking into it.

**Comment by artmasa** [comment]
I will go ahead and close this issue
